### PR TITLE
Adds FileSafe extension

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
FileSafe extensions from here - https://github.com/standardnotes/filesafe-bar

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
Hey @kylejbrk - can we merge this? This was missing earlier from the repo

**Comment by ashutoshsaboo** [comment]
working already - https://raw.githubusercontent.com/ashutoshsaboo/standard-notes-open-extended/gh-pages/file-safe/index.json

**Comment by ashutoshsaboo** [comment]
can you merge this PR - @kylejbrk ?

**Comment by kylejbrk** [comment]
Looks like the url is off in your index.json
image

Regardless I think this is safe to add for now. Thanks.

**Comment by ashutoshsaboo** [comment]
That must have been something wrong with fork's github action setup - the url field looks okay here - https://raw.githubusercontent.com/kylejbrk/standard-notes-open-extended/gh-pages/file-safe/index.json

**Pull request merged**
